test_that("SqliteDatabase.java test", {
  tempDbDir = tempdir()
  file.copy("./data/ResSimTest_20200101.db", tempDbDir)
  db = openEnsemblesFile(paste0(tempDbDir, "\\ResSimTest_20200101.db"), mode="open")
  id = .jnew("hec.RecordIdentifier", "Kanektok.BCAC1", "flow")
  ets = db$getEnsembleTimeSeries(id)
  cumulativeComputable = .jnew("hec.ensemble.stats.CumulativeComputable")
  cumulative = new(J("hec.ensemble.stats.NDayMultiComputable"), cumulativeComputable, as.integer(2))
  percentileCompute = new(J("hec.ensemble.stats.PercentilesComputable"), .jfloat(0.95))
  twoStep = .jcast(new(J("hec.ensemble.stats.TwoStepComputable"), cumulative, percentileCompute, FALSE), new.class="hec/ensemble/stats/SingleComputable", check=T)
  #twoStep = .jnew("hec.ensemble.stats.TwoStepComputable", cumulative, percentileCompute, FALSE)
  #.jmethods(ets, "computeSingleValueSummary")
  #output = .jcall(ets, returnSig="hec/metrics/MetricCollectionTimeSeries", method="computeSingleValueSummary", twoStep)
  output = ets$computeSingleValueSummary(.jcast(twoStep, "hec/ensemble/stats/SingleComputable", check=T))
  db$write(output)

  ids = db$getMetricTimeSeriesIDs()
  mcts = db$getMetricCollectionTimeSeries(ids$toArray()[[1]])
  expect_equal(3, mcts$getIssueDates()$size())
})
